from __future__ import annotations

from cxreason.gates.cardiomegaly import CardiomegalyRuleGate
from cxreason.gates.rules import (
    AllBinaryMeasurementsRuleGate,
    AnyMeasurementThresholdRuleGate,
    DirectionNotFlatRuleGate,
    MeasurementRangeRuleGate,
    MeasurementThresholdRuleGate,
)
from cxreason.gates.structured import BinaryFieldsGate, ChoiceFieldGate, NumericRangeGate
from cxreason.tasks.base import MinMaxRatioCheck, RatioCheck, TaskSpec


TASK_REGISTRY: dict[str, TaskSpec] = {
    "aortic_knob_enlargement": TaskSpec(
        name="aortic_knob_enlargement",
        display_name="Aortic Knob Enlargement",
        preferred_criterion="aortic knob to trachea width ratio",
        criterion_terms=("aortic knob", "trachea", "ratio"),
        stage2_fields=(
            "aortic_knob_xmin",
            "aortic_knob_xmax",
            "trachea_point_right",
            "trachea_point_left",
            "viewposition",
        ),
        stage3_fields=("aortic_knob_width", "trachea_width", "ratio"),
        stage3_numeric_fields=("aortic_knob_width", "trachea_width", "ratio"),
        ratio_checks=(RatioCheck("ratio", "aortic_knob_width", "trachea_width"),),
        final_field="aortic_knob_enlargement",
        final_gate=MeasurementThresholdRuleGate(
            "aortic_knob_enlargement",
            "ratio",
            threshold=2.495,
            operator=">",
        ),
    ),
    "ascending_aorta_enlargement": TaskSpec(
        name="ascending_aorta_enlargement",
        display_name="Ascending Aorta Enlargement",
        preferred_criterion="ascending aorta area beyond heart-trachea reference line",
        criterion_terms=("ascending aorta", "ascending aortic", "heart", "trachea"),
        stage2_fields=("heart_point", "trachea_point", "viewposition"),
        stage3_fields=("ratio",),
        stage3_numeric_fields=("ratio",),
        stage3_extra_gates=(
            NumericRangeGate({"ratio": (0.0, 1.0)}, stage_label="stage3_measurement"),
        ),
        final_field="ascending_aorta_enlargement",
        final_gate=MeasurementThresholdRuleGate(
            "ascending_aorta_enlargement",
            "ratio",
            threshold=0.1,
            operator=">=",
        ),
        notes="Stage 3 ratio is produced by CheXStruct from a mask-area relation.",
    ),
    "cardiomegaly": TaskSpec(
        name="cardiomegaly",
        display_name="Cardiomegaly",
        preferred_criterion="cardiothoracic ratio (CTR)",
        criterion_terms=("cardiothoracic ratio", "ctr"),
        stage2_fields=(
            "heart_xmin",
            "heart_xmax",
            "lung_xmin",
            "lung_xmax",
            "viewposition",
        ),
        stage2_numeric_fields=("heart_xmin", "heart_xmax", "lung_xmin", "lung_xmax"),
        stage3_fields=("heart_width", "lung_width", "ctr"),
        stage3_numeric_fields=("heart_width", "lung_width", "ctr"),
        ratio_checks=(RatioCheck("ctr", "heart_width", "lung_width"),),
        final_field="cardiomegaly",
        final_gate=CardiomegalyRuleGate(),
    ),
    "carina_angle": TaskSpec(
        name="carina_angle",
        display_name="Carina Angle",
        preferred_criterion="carina angle at the tracheal bifurcation",
        criterion_terms=("carina angle", "tracheal bifurcation", "angle"),
        stage2_fields=("point_1", "point_2", "point_3", "viewposition"),
        stage3_fields=("angle",),
        stage3_numeric_fields=("angle",),
        stage3_extra_gates=(
            NumericRangeGate({"angle": (0.0, 180.0)}, stage_label="stage3_measurement"),
        ),
        final_field="carina_angle",
        final_gate=MeasurementRangeRuleGate(
            "carina_angle",
            "angle",
            low=39.5,
            high=80.5,
        ),
    ),
    "descending_aorta_enlargement": TaskSpec(
        name="descending_aorta_enlargement",
        display_name="Descending Aorta Enlargement",
        preferred_criterion="descending aorta to trachea width ratio",
        criterion_terms=("descending aorta", "descending aortic", "trachea", "ratio"),
        stage2_fields=(
            "trachea_point_right",
            "trachea_point_left",
            "desc_aorta_point_right",
            "desc_aorta_point_left",
            "viewposition",
        ),
        stage3_fields=("desc_aorta_width", "trachea_width", "ratio"),
        stage3_numeric_fields=("desc_aorta_width", "trachea_width", "ratio"),
        ratio_checks=(RatioCheck("ratio", "desc_aorta_width", "trachea_width"),),
        final_field="descending_aorta_enlargement",
        final_gate=MeasurementThresholdRuleGate(
            "descending_aorta_enlargement",
            "ratio",
            threshold=2.5,
            operator=">=",
        ),
    ),
    "descending_aorta_tortuous": TaskSpec(
        name="descending_aorta_tortuous",
        display_name="Descending Aorta Tortuosity",
        preferred_criterion="descending aorta curvature across serial boundary points",
        criterion_terms=("descending aorta", "tortuous", "curvature", "tortuosity"),
        stage2_fields=("point_1", "point_2", "point_3", "point_4", "point_5", "point_6", "viewposition"),
        stage3_fields=("curvature",),
        stage3_numeric_fields=("curvature",),
        stage3_extra_gates=(
            NumericRangeGate({"curvature": (0.0, 0.02)}, stage_label="stage3_measurement"),
        ),
        final_field="descending_aorta_tortuous",
        final_gate=MeasurementThresholdRuleGate(
            "descending_aorta_tortuous",
            "curvature",
            threshold=0.00085,
            operator=">=",
        ),
    ),
    "inclusion": TaskSpec(
        name="inclusion",
        display_name="Lung Inclusion",
        preferred_criterion="adequate inclusion of lung apex, side, and bottom regions",
        criterion_terms=("inclusion", "apex", "side", "bottom", "lung"),
        stage2_fields=(
            "point_apex_right_lung",
            "point_apex_left_lung",
            "point_side_right_lung",
            "point_side_left_lung",
            "point_bottom_right_lung",
            "point_bottom_left_lung",
            "viewposition",
        ),
        stage3_fields=(
            "label_side_right_lung",
            "label_side_left_lung",
            "label_apex_right_lung",
            "label_apex_left_lung",
            "label_bottom_right_lung",
            "label_bottom_left_lung",
            "ratio_apex_right_lung",
            "ratio_apex_left_lung",
            "ratio_side_right_lung",
            "ratio_side_left_lung",
            "ratio_bottom_right_lung",
            "ratio_bottom_left_lung",
        ),
        stage3_numeric_fields=(
            "label_side_right_lung",
            "label_side_left_lung",
            "label_apex_right_lung",
            "label_apex_left_lung",
            "label_bottom_right_lung",
            "label_bottom_left_lung",
            "ratio_apex_right_lung",
            "ratio_apex_left_lung",
            "ratio_side_right_lung",
            "ratio_side_left_lung",
            "ratio_bottom_right_lung",
            "ratio_bottom_left_lung",
        ),
        stage3_extra_gates=(
            BinaryFieldsGate(
                (
                    "label_side_right_lung",
                    "label_side_left_lung",
                    "label_apex_right_lung",
                    "label_apex_left_lung",
                    "label_bottom_right_lung",
                    "label_bottom_left_lung",
                ),
                stage_label="stage3_measurement",
            ),
            NumericRangeGate(
                {
                    "ratio_apex_right_lung": (0.0, 1.0),
                    "ratio_apex_left_lung": (0.0, 1.0),
                    "ratio_side_right_lung": (0.0, 1.0),
                    "ratio_side_left_lung": (0.0, 1.0),
                    "ratio_bottom_right_lung": (0.0, 1.0),
                    "ratio_bottom_left_lung": (0.0, 1.0),
                },
                stage_label="stage3_measurement",
            ),
        ),
        final_field="inclusion",
        final_gate=AllBinaryMeasurementsRuleGate(
            "inclusion",
            (
                "label_side_right_lung",
                "label_side_left_lung",
                "label_apex_right_lung",
                "label_apex_left_lung",
                "label_bottom_right_lung",
                "label_bottom_left_lung",
            ),
        ),
        notes="Stage 3 is a collection of per-region inclusion recognitions and ratios.",
    ),
    "inspiration": TaskSpec(
        name="inspiration",
        display_name="Inspiration Level",
        preferred_criterion="right posterior rib count at the mid-clavicular line",
        criterion_terms=("inspiration", "rib", "mid-clavicular", "posterior"),
        stage2_fields=("mid-clavicular_line(x)", "viewposition"),
        stage3_fields=("rib_position",),
        stage3_numeric_fields=("rib_position",),
        stage3_extra_gates=(
            NumericRangeGate({"rib_position": (0.0, 12.0)}, stage_label="stage3_measurement"),
        ),
        final_field="inspiration",
        final_gate=MeasurementThresholdRuleGate(
            "inspiration",
            "rib_position",
            threshold=8,
            operator="<=",
        ),
    ),
    "mediastinal_widening": TaskSpec(
        name="mediastinal_widening",
        display_name="Mediastinal Widening",
        preferred_criterion="mediastinal to chest width ratio (MCR)",
        criterion_terms=("mediastinal", "mediastinum", "mcr", "chest width"),
        stage2_fields=(
            "mediastinum_xmin",
            "mediastinum_xmax",
            "lung_xmin",
            "lung_xmax",
            "viewposition",
        ),
        stage2_numeric_fields=("mediastinum_xmin", "mediastinum_xmax", "lung_xmin", "lung_xmax"),
        stage3_fields=("mediastinum_width", "lung_width", "mcr"),
        stage3_numeric_fields=("mediastinum_width", "lung_width", "mcr"),
        ratio_checks=(RatioCheck("mcr", "mediastinum_width", "lung_width"),),
        final_field="mediastinal_widening",
        final_gate=MeasurementThresholdRuleGate(
            "mediastinal_widening",
            "mcr",
            threshold=0.245,
            operator=">=",
            viewposition_thresholds={"PA": 0.245, "AP": 0.325},
        ),
    ),
    "projection": TaskSpec(
        name="projection",
        display_name="Projection",
        preferred_criterion="scapular overlap ratio with lung fields",
        criterion_terms=("projection", "scapular", "scapula", "overlap", "lung"),
        stage2_fields=(
            "scapular_region_right",
            "overlap_region_right",
            "scapular_region_left",
            "overlap_region_left",
            "viewposition",
        ),
        stage3_fields=(
            "scapular_region_right",
            "overlap_region_right",
            "ratio_right",
            "scapular_region_left",
            "overlap_region_left",
            "ratio_left",
        ),
        stage3_numeric_fields=(
            "scapular_region_right",
            "overlap_region_right",
            "ratio_right",
            "scapular_region_left",
            "overlap_region_left",
            "ratio_left",
        ),
        ratio_checks=(
            RatioCheck("ratio_right", "overlap_region_right", "scapular_region_right"),
            RatioCheck("ratio_left", "overlap_region_left", "scapular_region_left"),
        ),
        final_field="projection",
        final_gate=AnyMeasurementThresholdRuleGate(
            "projection",
            ("ratio_right", "ratio_left"),
            threshold=0.3,
            operator=">=",
        ),
    ),
    "rotation": TaskSpec(
        name="rotation",
        display_name="Rotation",
        preferred_criterion="clavicle-to-midline distance symmetry ratio",
        criterion_terms=("rotation", "clavicle", "midline", "spinous", "ratio"),
        stage2_fields=(
            "medial_end_right_clavicle",
            "medial_end_left_clavicle",
            "midline_points",
            "midline_point_right_clavicle",
            "midline_point_left_clavicle",
            "viewposition",
        ),
        stage3_fields=("distance_right", "distance_left", "ratio"),
        stage3_numeric_fields=("distance_right", "distance_left", "ratio"),
        minmax_ratio_checks=(MinMaxRatioCheck("ratio", "distance_right", "distance_left"),),
        final_field="rotation",
        final_gate=MeasurementThresholdRuleGate(
            "rotation",
            "ratio",
            threshold=0.395,
            operator="<",
        ),
    ),
    "trachea_deviation": TaskSpec(
        name="trachea_deviation",
        display_name="Trachea Deviation",
        preferred_criterion="tracheal midline deviation direction across serial points",
        criterion_terms=("trachea", "tracheal", "deviation", "direction"),
        stage2_fields=(
            "point_1",
            "point_2",
            "point_3",
            "point_4",
            "point_5",
            "point_6",
            "point_7",
            "point_8",
            "point_9",
            "viewposition",
        ),
        stage3_fields=("direction_per_pnt", "direction"),
        stage3_extra_gates=(
            ChoiceFieldGate(
                "direction",
                ("flat", "left", "right", "left&right", "right&left"),
                stage_label="stage3_measurement",
            ),
        ),
        final_field="trachea_deviation",
        final_gate=DirectionNotFlatRuleGate("trachea_deviation"),
    ),
}


def get_task_spec(task: str) -> TaskSpec:
    try:
        return TASK_REGISTRY[task]
    except KeyError as exc:
        valid = ", ".join(sorted(TASK_REGISTRY))
        raise ValueError(f"Unknown task: {task}. Valid tasks: {valid}") from exc


def list_task_names() -> tuple[str, ...]:
    return tuple(TASK_REGISTRY)
